export type NodeStatus =
  | 'idle'
  | 'running'
  | 'done'
  | 'failed'
  | 'cancelled'
  | 'interrupted';

export type RunStatus = NodeStatus;

export type NodeKind = 'coder' | 'critique' | 'config';

/**
 * Session handling for the coder spawned beneath a config node (and for the
 * config node's own record of what it did):
 * - `retain` — resume the branch's existing coder session under the new coder.
 *   Only valid when the new coder is session-compatible (same adapter `kind`)
 *   with the session being resumed. Wired like Continue (shared branch anchor).
 * - `reset`  — start a fresh session from the current code. Wired like Fork
 *   (own branch off the ancestor coder's tip). The only option for an
 *   incompatible switch (e.g. claude-code → a different tool).
 */
export type SessionPolicy = 'retain' | 'reset';

export type ArtifactKind = 'code' | 'video' | 'thumbnail' | 'frame' | 'log';

export type RunPhase = 'coding' | 'rendering' | 'critiquing';

/**
 * Who produced a critique. `human` — written by the artist (human-critic mode,
 * or the "Critique manually" override on a node whose configured critic is a
 * model). `model` — generated by a critic adapter, tagged with the adapter
 * `kind` and, when the adapter exposes a fixed model, the `model` id it ran.
 */
export interface CritiqueAuthor {
  kind: 'human' | 'model';
  /** Critic adapter kind that produced it, e.g. 'claude-code'. Model authors only. */
  critic?: string;
  /** Model id the critic ran, e.g. 'claude-sonnet-4-6'. Set when the adapter exposes one. */
  model?: string;
}

export interface Critique {
  overall: string;
  rating?: number;
  strengths: string[];
  weaknesses: string[];
  suggestions: string[];
  /**
   * Generic rules the critic believes should apply to every future render in
   * this project. Surfaced in the UI with one-click promotion to LESSONS.md.
   * Optional so older runs (and human-only critics) round-trip cleanly.
   */
  proposedRules?: string[];
  /**
   * Who authored this critique. Optional so older runs round-trip cleanly;
   * the orchestrator stamps it on every newly-stored critique (model author
   * for adapter runs, human author for manual entry).
   */
  author?: CritiqueAuthor;
}

export interface RunError {
  phase: RunPhase | 'startup';
  message: string;
  stack?: string;
  /**
   * Set when the run failed because post-coder validation checks exhausted
   * their retry budget. Lets the UI render which check failed and the last
   * captured output, distinct from a generic exception.
   */
  validation?: {
    check: string;
    attempts: number;
    output: string;
  };
}

export interface AdapterConfigSnapshot {
  /** `args.name` records which named coder from the registry actually ran. */
  coder: { kind: string; args?: { name?: string } };
  /** `model` records the critic's model id when the adapter exposes a fixed one. */
  critic: { kind: string; model?: string; args?: unknown };
  renderer: { kind: string; args?: unknown };
}
